//go:build ignore

package main

import (
	"flag"
	"go/token"
	"os"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

const mode packages.LoadMode = packages.NeedName

func main() {

	pattern := flag.String("pattern", "./...", "Go package pattern")

	var fset = token.NewFileSet()
	cfg := &packages.Config{Fset: fset, Mode: mode, Dir: "."}

	pkgs, err := packages.Load(cfg, *pattern)
	if err != nil {
		panic(err)
	}

	var days []string
	for _, pkg := range pkgs {
		if strings.HasPrefix(pkg.Name, "day") {
			days = append(days, pkg.Name)
		}
	}

	f, err := os.Create("solution_gen.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Days []string
	}{
		Days: days,
	})

}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
package main

import (
{{- range .Days }}
	"{{"github.com/ryeguard/advent-of-code/2024/"}}{{ printf "%s" . }}"
{{- end }}
)

var solutionFuncs = [](func([]string) (int, int, error)){
{{- range .Days }}
	{{ printf "%s" . }}{{".Solution"}},
{{- end }}
}
`))
