// Code generated by go generate; DO NOT EDIT.
package main

import (
	"github.com/ryeguard/advent-of-code/2024/day00"
	"github.com/ryeguard/advent-of-code/2024/day01"
	"github.com/ryeguard/advent-of-code/2024/day02"
	"github.com/ryeguard/advent-of-code/2024/day03"
	"github.com/ryeguard/advent-of-code/2024/day04"
	"github.com/ryeguard/advent-of-code/2024/day05"
	"github.com/ryeguard/advent-of-code/2024/day06"
	"github.com/ryeguard/advent-of-code/2024/day07"
	"github.com/ryeguard/advent-of-code/2024/day08"
	"github.com/ryeguard/advent-of-code/2024/day09"
)

var solutionFuncs = [](func([]string) (int, int, error)){
	day00.Solution,
	day01.Solution,
	day02.Solution,
	day03.Solution,
	day04.Solution,
	day05.Solution,
	day06.Solution,
	day07.Solution,
	day08.Solution,
	day09.Solution,
}
