// Code generated by go generate; DO NOT EDIT.
package main

import (
	"github.com/ryeguard/advent-of-code/2024/day00"
	"github.com/ryeguard/advent-of-code/2024/day01"
	"github.com/ryeguard/advent-of-code/2024/day02"
	"github.com/ryeguard/advent-of-code/2024/day03"
	"github.com/ryeguard/advent-of-code/2024/day04"
	"github.com/ryeguard/advent-of-code/2024/day05"
	"github.com/ryeguard/advent-of-code/2024/day06"
	"github.com/ryeguard/advent-of-code/2024/day07"
	"github.com/ryeguard/advent-of-code/2024/day08"
	"github.com/ryeguard/advent-of-code/2024/day10"
	"github.com/ryeguard/advent-of-code/2024/day11"
)

var solutionFuncs = [](func([]string) (int, int, error)){
	0: day00.Solution,
	1: day01.Solution,
	2: day02.Solution,
	3: day03.Solution,
	4: day04.Solution,
	5: day05.Solution,
	6: day06.Solution,
	7: day07.Solution,
	8: day08.Solution,
	10: day10.Solution,
	11: day11.Solution,
}
