name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2024

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Generate coverage file
        run: go test -v ./...

      - name: Go coverage report
        uses: ryeguard/go-coverage-report@v0.1.1
        with:
          badge-title: "2024 Go Coverage"
          modules-dir: "2024"

        # Only run the action on push (to main)
        # PRs lack permission to update the Wiki, nor would you want unmerged PRs to do so
        if: github.event_name == 'push'
        # If tests pass, the problem might be with the action itself, not your code
        continue-on-error: true
