name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: ./2024

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Test
        run: go test -v ./...

      - name: Go coverage report
        uses: ncruces/go-coverage-report@v0.3.0
        with:
          badge-title: "2024 Go Coverage"
          output-dir: "2024"

        # Only run the action on push (to main)
        # PRs lack permission to update the Wiki, nor would you want unmerged PRs to do so
        if: |
          github.event_name == 'push'

        # If tests pass, the problem might be with the action itself, not your code
        continue-on-error: true
